export * from './aboutHome/aboutHome';
export * from './aboutShop/aboutShop';
export * from './basketContent/basketContent';
export * from './footer/footer';
export * from './header/header';
export * from './homeCards/homeCards';
export * from './shopContent/shopContent';
export * from './tittle/tittle';
export * from './tittleHome/tittleHome';
